### ISSUE TITLE
lack of history

### ISSUE THREAD

**Issue by laurencefass** [synereo/special-k#2]
Im a little confused also that there are no issues/labels/milestones in the this queue despite contributions from numerous developers. how did the contributers communicate? Has SpecialK been stress tested? How does it stand up? If it hasnt (yet) how do we stress test it?

**Comment by leithaus** [comment]
@laurencefass - this was forked from the original repo. The issues were kept in a code.google.com issue tracker.

**Comment by laurencefass** [comment]
can you port test metrics here - or sketch out relevant test scenario so we can create them?
