### ISSUE TITLE
load/performance testing.

### ISSUE THREAD

**Issue by laurencefass** [synereo/special-k#4]
Under what conditions has special-k been stress tested? How does it stand up? If it hasn't (yet) how do we stress test it? What are the design constraints? Under what conditions will it work well? Not so well?

**Comment by leithaus** [comment]
Yes, it has been stress tested as a part of performance testing before www.protunity.com went live in March 2013. It was tested with both hand written stress tests and loadrunner. We know what the hotspots are and have a rich backlog of things we want to improve.
